version: "3.7"

# Notas: sebe otorgar permisos para acceso remoto al usuario 'microservicio'
# grant all privileges on *.* to 'microservicio'@'%' identified by 'secr3t!';
services:
  db:
    image: mysql:5.7
    #image: debezium/example-mysql:2.5.1.Final
    restart: always
    environment:
      MYSQL_DATABASE: 'partyreferencedata'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'microservicio'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'secr3t!'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'secr3t!'
    ports:
    # <Port exposed> : <MySQL Port running inside container>
    - '3306:3306'
    expose:
      # Opens port 3306 on the container
    - '3306'
    # Where our data will be persisted
    volumes:
    - "my-db-data:/var/lib/mysql:Z"
    - "my-db-logs:/var/log/mysql:Z"
    - "./my.cnf:/etc/mysql/conf.d/my.cnf"
    - "./scripts/:/docker-entrypoint-initdb.d/"
  #
  ##
  #
  service:
    image: xnet/partyreferencedata:1.0.2
    restart: always
    ports:
    - "8080:8082"
    env_file:
    - .env
    volumes:
    - "../api/src/main/resources/application-dev.yaml:/opt/config/application.yaml"
# Names our volume
volumes:
  my-db-data:
  my-db-logs:
