- name: ensure packages are installed
  package:
    name: "{{ item }}"
    status: present
    update: true
  with_items:
  - git
  - ca-certificates
  - curl
  - gnupg

# sudo install -m 0755 -d /etc/apt/keyrings

- name: install gpg for Docker
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: change mode
  file:
    src: /etc/apt/keyrings/docker.gpg
    mode: "a+r" 

- name: ensure package in repository
  shell: |
    echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# sudo apt-get update

- name: ensure docker packages are installed
  package:
    name: "{{ item }}"
    status: present
    update: true
  with_items:
  - docker-ce docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

- name: enable current user in docker group
  shell: |
    usermod -aG docker $USER
   
- name: restart docker
  service:
    name: docker
    status: restarted
  # systemctl restart docker


- name: ensure docker-compose is installed
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "+x"

# sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

# git clone https://github.com/xnet-training/elastic
# 1  docker ps
# 2  ls -la
# 3  cat es-instances.yml 
# 4  cat apm-server.yml 
# 5  cat apm-server.yml | grep 172
# 6  ls -la
# 7  cat .env | grep 172
# 8  cat docker-compose.yaml | gpre 172
# 9  cat docker-compose.yaml | grep 172
# 0  cat kibana.yml | grep 172
# 1  sudo docker-compose up -d
# 2  sudo docker ps
# 3  clear
# 4  sudo docker-compose up -d
# 5  ls -la
# 6  vi docker-compose.yaml 
# 7  sudo chown ubuntu heartbeat.yml 
# 8  sudo docker-compose up -d heartbeast01
# 9  sudo docker-compose up -d heartbeats01
# 0  sudo docker-compose logs heartbeast01
# 1  sudo docker-compose up heartbeats01
# 2  pwd
# 3  cat /home/ubuntu/elastic/heartbeat.yml
# 4  ls -la
# 5  sudo rm -rd heartbeat.yml/
# 6  ls -la
# 7  git pull
# 8  ls -la
# 9  vi heartbeat.yml
# 70  git pull
# 71  ls -la
# 72  sudo docker-compose up -d heartbeats01
# 73  sudo docker-compose logs heartbeats01
# 74  sudo docker-compose up -d metrics01
# 75  cat docker-compose.yaml 
# 76  sudo docker-compose up -d metricbeats
# 77  sudo docker-compose up -d metricbeat01
# 78  sudo docker-compose logs metricbeat01
# 79  vi docker-compose.yaml 
# 80  sudo docker-compose up -d metricbeat01
# 81  sudo docker-compose logs metricbeat01
# 82  sudo chmod go-w /usr/share/metricbeat/metricbeat.yml
# 83  ls -la
# 84  sudo chown root metricbeat.yml
# 85  vi docker-compose.yaml 
# 86  sudo docker-compose up -d metricbeat01
# 87  sudo docker ps
# 88  sudo docker-compose logs metricbeat01
# 89  ls -la
# 90  sudo chown root:root metricbeat.yml
# 91  sudo docker-compose up metricbeat01
# 92  sudo docker-compose 
# 93  sudo docker ps
# 94  sudo chown root:root metricbeat.yml 
# 95  sudo docker-compose up metricbeat01
# 96  vi docker-compose.yaml 
# 97  sudo docker-compose up metricbeat01
# 98  vi docker-compose.yaml 
# 99  sudo docker-compose up metricbeat01
# 00  vi docker-compose.yaml 
# 01  sudo docker-compose up metricbeat01
# 02  ls -la
# 03  sudo chown ubuntu:ubuntu metricbeat.yml
# 04  ls -la
# 05  sudo docker-compose up metricbeat01
# 06  sudo chown ubuntu:root metricbeat.yml
# 07  sudo docker-compose up metricbeat01
# 08  sudo docker-compose logs metricbeat01
# 09  sudo chown root:root metricbeat.yml
# 10  sudo docker-compose logs metricbeat01
# 11  sudo docker-compose up metricbeat01
# 12  sudo chmod go-w metricbeat.yml 
# 13  sudo docker-compose up metricbeat01
# 14  sudo docker-compose logs metricbeat01
# 15  sudo docker ps
# 16  sudo docker-compose stop
# 17  ls -la
# 18  sudo chown root:ubuntu metricbeat.yml 
# 19  sudo chown root:ubuntu filebeat.yml 
# 20  sudo docker-compose up -d
# 21  docker ps
# 22  sudo docker ps
# 23  docker ps
# 24  sudo docker ps
# 25  ls -la
# 26  sudo docker ps
# 27  docker-compose logs metricbeat01
# 28  sudo docker-compose logs metricbeat01
# 29  sudo docker-compose logs heartbeat01
# 30  sudo docker-compose logs heartbeats01
# 31  clear
# 32  sudo docker ps
# 33  vi heartbeat.yml 
# 34  sudo docker-compose up -d heartbeats01
# 35  sudo docker-compose rm -sfv
# 36  sudo docker volume ls
# 37  sudo docker volume rm caja*
# 38  sudo docker volume rm caja
# 39  sudo docker volume rm $(sudo docker volume volume ls | awk '{print $2}')
# 40  sudo docker volume ls | awk '{print $2}')
# 41  sudo docker volume rm $(sudo docker volume ls | awk '{print $2}')
# 42  sudo docker volume ls
# 43  sudo docker compose up -d
# 44  sudo docker 
# 45  sudo docker compose up es01
# 46  sudo docker compose up -d es01
# 47  cd ..
# 48  curl http://www.cmac-cusco.com.pe
# 49  curl -v http://www.cmac-cusco.com.pe
# 50  ls -la
# 51  cd elastic/
# 52  git add heartbeat.yml 
# 53  git commit -am "add: caja cusco"
# 54  sudo docker compose up -d es01
# 55  sudo docker compose ps
# 56  sudo docker compose restart es01
# 57  sudo docker compose logs -f es01
# 58  netstat
# 59  sudo apt install net-tools
# 60  sudo docker compose logs -f es01
# 61  ps
# 62  netstat
# 63  top
# 64  cd elastic/
# 65  ls -l
# 66  docker compose ps
# 67  docker compose up -d es01
# 68  top
# 69  docker compose status es01
# 70  docker compose logs es01
# 71  vi docker-compose.yaml 
# 72  docker compose restart es01
# 73  docker compose logs -f es01 --tail 100
# 74  top
# 75  clear
# 76  cat docker-compose.yaml 
# 77  docker compose ps
# 78  docker compose status filebeats01
# 79  docker compose restart filebeats01
# 80  docker compose restart filebeat01
# 81  docker compose logs -f filebeat01
# 82  sudo chmod go-w filebeat.yml 
# 83  docker compose restart filebeat01
# 84  docker compose logs -f filebeat01
# 85  docker compose logs -f es01
# 86  vi docker-compose.yaml 
# 87  docker compose logs -f es01
# 88  ckjfdsfds
# 89  docker compose logs -f es01 --tail 20
# 90  vi docker-compose.yaml 
# 91  docker compose restart es01
# 92  docker compose logs -f es01 --tail 20
# 93  df -h
# 94  docker compose ps
# 95  vi docker-compose.yaml 
# 96  docker compose rm -fsv es01
# 97  docker compose upd -d es01
# 98  docker compose up -d es01
# 99  docker compose logs -f es01 --tail 20
#  200  history