apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.connectionSecret" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "chart.connectionSecret" . | quote}}
type: kubernetes.io/service-account-token
data:
  #DATABASE: V1NPMkNBUkJPTl9EQg==
  PASSWORD: {{ b64enc .Values.schema.user.password }}
  # USER: user
  USER: {{ b64enc .Values.schema.user.name }}
